site_name: DANDI documentation
repo_name: "dandi/handbook"
repo_url: "https://github.com/dandi/handbook"
copyright: "CC-BY 4.0"

# This will use Material them
theme:
  name: "material"
  language: "en"
  favicon: img/favicon.png
  logo: img/dandi-logo-square_sw.png
  palette:
    primary: "dark blue"
    accent: "light blue"

# Pages
nav:
  - Welcome: "index.md"
  - Introduction: "01_introduction.md"
  - Using DANDI: "10_using_dandi.md"
  - Developer Guide:
    - Notes: "developer/notes.md"
  - Project structure: "20_project_structure.md"
  #- Schema: "30_schema.md"
  - FAQ: "98_FAQ.md"
  #- Glossary: "99_glossary.md"
  - About this doc: "100_about_this_doc.md"

# list of extension
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.critic
